version: "3"

services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong

  kong:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-databasex
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgres://kong:kong@kong-database:5432/konga
    ports:
      - "1337:1337"
